name: "Deploy dwaves-app to GCS"
description: "Deploy dwaves-app to GCS"
runs:
    using: composite
    steps:
      - name: Retrieve environment variables 🌎
        working-directory:  ${{ env.PROJECT_DIRECTORY }}
        shell: bash
        run: |-
          source ${{ env.PROPERTIES_SCRIPT }} && doppler_setup

      - name: NPM install
        working-directory:  ${{ env.PROJECT_DIRECTORY }}
        shell: bash
        run: |-
          npm install

      - name: Build 🏗
        working-directory:  ${{ env.PROJECT_DIRECTORY }}
        shell: bash
        run: |-
          CI="false" npm run deploy-build

      - name: Deploy  🚀
        working-directory:  ${{ env.PROJECT_DIRECTORY }}
        shell: bash
        run: |-
          source ${{ env.PROPERTIES_SCRIPT }} && doppler_setup
          export gcp_environment="${{ env.APP }}-$ENVIRONMENT"
          export deploy_url=$BUCKET_NAME
          gsutil rsync -R build/ gs://$deploy_url
          echo "Deployed to $gcp_environment environment: $deploy_url"