name: "Deploy dwaves-app to GCS"
description: "Deploy dwaves-app to GCS"
runs:
    using: composite
    steps:
      - name: Retrieve environment variables 🌎
        shell: bash
        run: |-
          source ${{ env.PROPERTIES_SCRIPT }} && doppler_setup

      - name: NPM install
        shell: bash
        run: npm install

      - name: Build 🏗
        shell: bash
        run: |-
          CI="false" npm run build

      - name: Deploy Production 🚀
        shell: bash
        run: |-
          source ${{ env.PROPERTIES_SCRIPT }} && doppler_setup
          export gcp_environment="${{ env.APP }}-$ENVIRONMENT"
          export deploy_url=$BUCKET_NAME
          gsutil rsync -R build/ gs://$deploy_url
          echo "Deployed to $gcp_environment environment: $deploy_url"