version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/backend'
    schedule:
      interval: weekly
      time: '12:00'
      timezone: 'Europe/Paris'
    labels:
      - 'backend'
      - 'security'
      - 'dependency-update'
    assignees:
      - 'dependabot-bot'
      - 'alexandre-pinon'
    reviewers:
      - 'alexandre-pinon'
    target-branch: 'staging'
    open_pull_requests_limit: 3

  - package-ecosystem: 'npm'
    directory: '/frontend'
    schedule:
      interval: 'weekly'
      time: '12:00'
      timezone: 'Europe/Paris'
    labels:
      - 'frontend'
      - 'security'
      - 'dependency-update'
    assignees:
      - 'dependabot-bot'
      - 'alexandre-pinon'
      - 'BryanSeychelles'
    reviewers:
      - 'alexandre-pinon'
      - 'BryanSeychelles'
    target-branch: 'staging'
    open_pull_requests_limit: 2


  - package-ecosystem: 'gradle'
    directory: '/mobile'
    schedule:
      interval: 'weekly'
    labels:
      - 'mobile'
      - 'security'
      - 'dependency-update'
    assignees:
      - 'dependabot-bot'
      - 'Bolrung'
    reviewers:
      - 'Bolrung'
    target-branch: 'staging'
    open_pull_requests_limit: 2


  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'architechture'
      - 'docker'
      - 'security'
      - 'dependency-update'
    assignees:
      - 'dependabot-bot'
      - 'Wbebey'
    reviewers:
      - 'Wbebey'
    target-branch: 'staging'
    open_pull_requests_limit: 2

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'architechture'
      - 'github-actions'
      - 'security'
      - 'dependency-update'
    assignees:
      - 'dependabot-bot'
      - 'Wbebey'
    reviewers:
      - 'Wbebey'
    target-branch: 'staging'
    open_pull_requests_limit: 2


  - package-ecosystem: 'terraform'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'architechture'
      - 'terraform'
      - 'security'
      - 'dependency-update'
    assignees:
      - 'dependabot-bot'
      - 'Wbebey'
    reviewers:
      - 'Wbebey'
    target-branch: 'staging'
    open_pull_requests_limit: 2
