repos:
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.14.2
    hooks:
      - id: ggshield
        stages: [commit]
        language: python
        entry: ggshield
        verbose: true
        # args: ['--api-key', '${GITGUARDIAN_API_KEY}']


