repos:
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.14.2
    hooks:
      - id: ggshield
        language_version: python3
        stages: [commit]
        verbose: true
        files: ^backend/smart-contracts/
        types_or: [javascript, jsx, ts, tsx]