name: Daploy to Staging
description: Deploy to Staging
runs:
    using: composite
    steps:
        - name: Use Node.js ${{ env.NODE_VERSION }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ env.NODE_VERSION }}

        - name: Unit Test 🧪
          working-directory: ${{ env.PROJECT_DIRECTORY }}
          shell: bash
          run: |-
            echo "Running  unit tests..."