name: Daploy to GCP
description: Deploy to GCP
runs:
  using: composite
  steps:
    - name: GCP authentification 🤑
      uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ env.GCP_SA_KEY }}
        project_id: ${{ env.GCP_PROJECT_ID }}

    - name: Retreive Cached Build folder
      id: cache-build
      uses: actions/cache@v3
      with:
        path: build/
        key: ${{ runner.os }}-build

    - name: Deploy 🚀
      shell: bash
      run: |-
        if [ ${{ github.ref }} == 'refs/heads/main' ]; then 
          export environment=${{ env.APP }}-production
          export deploy_url=${{ env.DWAVES_PRODUCTION_URL }}
          gsutil rsync -R build/ gs://$deploy_url
        elif [ ${{ github.ref }} == 'refs/heads/staging' ]; then
          export environment=${{ env.APP }}-staging
          export deploy_url=${{ env.DWAVES_STAGING_URL }}
          gsutil rsync -R build/ gs://$deploy_url
        fi
        echo "Deployed to $environment environment: $url"