name: Cron scheduled

on:
  push:
    paths:
      - "backend/jobs/**"
  schedule:
    - cron: "0 0 1 * *" # Run at 00:00 on day-of-month 1

env:
  NODE_VERSION: 16.x
  JOBS_DIRECTORY: backend/jobs
  DATABASE_DIRECTORY: backend/db
  ENV_VARS: ${{ secrets.DWAVES_JOBS_STAGING_ENV }}
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
  DISCORD_TEAM_ID: ${{ secrets.DISCORD_BACK_TEAM_ID }}

jobs:
  execute-script:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.JOBS_DIRECTORY }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Retrieve environment for jobs
        run: echo "${{ env.ENV_VARS }}" > .env

      - name: Install dependencies
        run: npm install

      - name: Build script 
        run: npm run build

      - name: Run script
        run: npm run start build/payArtists.js

      - name: Discord notification on success
        if: success()
        uses: ./.github/actions/discord/notification-on-success

      - name: Discord notification on failure
        if: failure()
        uses: ./.github/actions/discord/notification-on-failure