name: Debricked scan

on: 
  push:
  pull_request:
    branches:
      - staging

env:
  DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN }}

jobs:
  vulnerabilities-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: debricked/actions/scan@v1
      env:
        DEBRICKED_TOKEN: ${{ env.DEBRICKED_TOKEN }}