name: Dwaves-jobs

on:
  push:
    branches: 
      - feature/*
      - bugfix/*
      - hotfix/*
      - release/*
      - staging
      - main
    paths:
      - backend/jobs/**
  # pull_request:
  #   types: [opened, synchronize, reopened]
  #   branches:
  #     - staging
  #   paths:
  #     - backend/jobs/**

env:
    APP: dwaves-jobs
    NODE_VERSION: 16.x
    PROJECT_DIRECTORY: backend/jobs
    DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    DISCORD_TEAM_ID: ${{ secrets.DISCORD_BACK_TEAM_ID }} 
    SONAR_PROJECT_BASE_DIR: backend/jobs/
    SONAR_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_DWAVES_JOBS }}
    SONAR_PROJECT_KEY: ${{ secrets.DWAVES_JOBS_PROJECT_KEY }}

defaults:
  run:
    working-directory: "backend/jobs"

jobs:
  integration-test:
    name: Integretion Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 😇
        uses: actions/checkout@v3

      - name: Integration Tests 🏗
        uses: ./.github/actions/frontend/integration-test

      - name: Discord notification on failure
        if: failure()
        uses: ./.github/actions/discord/notification-on-failure

  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 😇
        uses: actions/checkout@v3

      - name: Unit Test 🧪
        uses: ./.github/actions/frontend/unit-test

      - name: Discord notification on failure
        if: failure()
        uses: ./.github/actions/discord/notification-on-failure

  code-analysis:
    name: Code Analysis
    runs-on: ubuntu-latest
    needs: [integration-test, unit-test]
    permissions: 
      contents: read
      pull-requests: write
    steps:
      - name: Checkout 😇
        uses: actions/checkout@v3

      - name: SonarCloud Scan
        uses: ./.github/actions/sonarcloud

      - name: Discord notification on success
        if: success()
        uses: ./.github/actions/discord/notification-on-success

      - name: Discord notification on failure
        if: failure()
        uses: ./.github/actions/discord/notification-on-failure