name: TAB - Dwaves-website  

on:
    push:
        branches: 
            - feature/*
            - bugfix/*
            - hotfix/*
            - release/*
        paths:
            - frontend/dwaves-website/**
    # pull_request:
    #     types: [opened, synchronize, reopened]
    #     branches:
    #         - staging
    #     paths:
    #         - frontend/dwaves-website/**

env:
    APP: dwaves-website
    PROJECT_DIRECTORY: frontend/dwaves-website
    DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    DISCORD_TEAM_ID: ${{ secrets.DISCORD_FRONT_TEAM_ID }} 
    SONAR_PROJECT_BASE_DIR: frontend/dwaves-website/
    SONAR_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_DWAVES_WEBSITE }}
    SONAR_PROJECT_KEY: ${{ secrets.DWAVES_WEBSITE_PROJECT_KEY }}
    NODE_VERSION: 16.x
    GCP_SA_KEY: ${{ secrets.TF_SA }}
    GCP_PROJECT_ID: ${{ secrets.DWAVES_PROJECT_ID }}

defaults:
    run:
        working-directory: "frontend/dwaves-website"

jobs:
    integration-test:
        name: Integretion Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 😇
              uses: actions/checkout@v3

            - name: Integration Tests 🏗
              uses: ./.github/actions/frontend/integration-test

            - name: Discord notification on failure
              if: failure()
              uses: ./.github/actions/discord/notification-on-failure

    unit-test:
        name: Unit Test
        runs-on: ubuntu-latest
        steps:

            - name: Checkout 😇
              uses: actions/checkout@v3

            - name: Unit Test 🧪
              uses: ./.github/actions/frontend/unit-test

            - name: Discord notification on failure
              if: failure()
              uses: ./.github/actions/discord/notification-on-failure

    code-analysis:
        name: Code Analysis
        runs-on: ubuntu-latest
        permissions: 
            contents: read
            pull-requests: write
        needs: [integration-test, unit-test]
        steps:
            - name: Checkout 😇
              uses: actions/checkout@v3

            - name: SonarCloud Scan
              uses: ./.github/actions/sonarcloud

            - name: Discord notification on success
              if: success()
              uses: ./.github/actions/discord/notification-on-success

            - name: Discord notification on failure
              if: failure()
              uses: ./.github/actions/discord/notification-on-failure