# TODO replace FRONT_ENV by an env with the name of the environment
name : Deploy Dwaves-website to Production

on:
    push:
        branches:
            - main
        paths:
            - frontend/dwaves-website/**

env: 
    APP: dwaves-website
    ENVIRONMENT: production
    PROJECT_DIRECTORY: frontend/dwaves-website
    DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    DISCORD_TEAM_ID: ${{ secrets.DISCORD_FRONT_TEAM_ID }} 
    SONAR_PROJECT_BASE_DIR: frontend/dwaves-website/
    SONAR_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_DWAVES_WEBSITE }}
    SONAR_PROJECT_KEY: ${{ secrets.DWAVES_WEBSITE_PROJECT_KEY }}
    NODE_VERSION: 16.x
    GCP_SA_KEY: ${{ secrets.TF_SA }}
    GCP_PROJECT_ID: ${{ secrets.DWAVES_PROJECT_ID }}
    FRONT_ENV: ${{ secrets.FRONT_ENV }}
    PRODUCTION_URL: ${{ secrets.DWAVES_WEBSITE_PRODUCTION_URL }}

defaults:
    run:
        working-directory: "frontend/dwaves-website"

jobs:
    integration-test:
        name: Integretion Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 😇
              uses: actions/checkout@v3

            - name: Integration Tests 🏗
              uses: ./.github/actions/frontend/integration-test

            - name: Discord notification on failure
              if: failure()
              uses: ./.github/actions/notification-on-failure

    unit-test:
        name: Unit Test
        runs-on: ubuntu-latest
        steps:

            - name: Checkout 😇
              uses: actions/checkout@v3

            - name: Unit Test 🧪
              uses: ./.github/actions/frontend/unit-test

            - name: Discord notification on failure
              if: failure()
              uses: ./.github/actions/discord/notification-on-failure

    code-analysis:
        name: Code Analysis
        runs-on: ubuntu-latest
        permissions: 
            contents: read
            pull-requests: write
        needs: [integration-test, unit-test]
        steps:
            - name: Checkout 😇
              uses: actions/checkout@v3

            - name: SonarCloud Scan
              uses: ./.github/actions/sonarcloud

            - name: Discord notification on failure
              if: failure()
              uses: ./.github/actions/discord/notification-on-failure

    deploy:
        name: Deploy to Production
        needs: [code-analysis]
        environment:
            name: dwaves-website-production
            url: https://dwaves.tonfrere.fr
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 😇
              uses: actions/checkout@v3

            - name: Discord notification ${{ env.ENVIRONMENT }} Deployment started
              uses: ./.github/actions/discord/notification-on-start-deployment

            - name: GCP authentification 🤑
              uses: google-github-actions/setup-gcloud@v0
              with:
                service_account_key: ${{ env.GCP_SA_KEY }}
                project_id: ${{ env.GCP_PROJECT_ID }}

            - name: Use Node.js ${{ env.NODE_VERSION }}
              uses: actions/setup-node@v3
              with:
                node-version: ${{ env.NODE_VERSION }}

            - name: Retrieve environment for ${{ env.ENVIRONMENT }} 🌎
              run: echo "${{ env.FRONT_ENV }}" > .env

            - name: NPM install
              run: npm install

            - name: Build 🏗
              run: |-
                CI='false' npm run build

            - name: Deploy Production 🚀
              if: ${{ github.ref }} == 'refs/heads/main'
              run: |-
                export environment="${{ env.APP }}-${{ env.ENVIRONMENT }}"
                export deploy_url=${{ env.PRODUCTION_URL }}
                gsutil rsync -R build/ gs://$deploy_url
                echo "Deployed to $environment environment: $deploy_url"

            - name: Discord notification on success
              if: success()
              uses: ./.github/actions/discord/notification-on-success

            - name: Discord notification on failure
              if: failure()
              uses: ./.github/actions/discord/notification-on-failure