name: Trivy Scanning

on:
  # push:
  #   branches:
  #     - master
  pull_request:
    branches:
      - staging
      - main
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  trivy-scan:
    name: Trivy IaC scan
    runs-on: ubuntu-latest
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          args: 'backend/api'
          # scan-ref: 'dwaves'
          hide-progress: false
          format: 'sarif'
          # exit-code: '1'
          output: 'trivy-results.sarif'
          security-checks: 'vuln,secret,config'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
          # vuln-type: 'os,library'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'